FROM python:3.10-slim

WORKDIR /app

# Install dependencies required for ML
RUN pip install --no-cache-dir scikit-learn==1.5.2 joblib==1.4.2 numpy==2.1.2

# Copy the backend ML code and artifacts
COPY backend/app/ml/ ./backend/app/ml/

# Copy the enclave app
COPY enclave/app.py ./enclave/app.py

# Add to Python path
ENV PYTHONPATH=/app

# Start the Enclave server
CMD ["python", "-u", "enclave/app.py"]
